version: "3.8"

services:
  backend:
    restart: always
    depends_on:
      - postgres
    build: .
    env_file:
      - .env
    ports:
    - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3

  postgres:
    restart: always
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=testcrt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3


volumes:
  postgres_data:
